CREATE TABLE CLIENTS(
   ID  SERIAL  PRIMARY KEY,
   LASTNAME    TEXT      NOT NULL,
   FIRSTNAME   TEXT      NOT NULL,
   PARENTNAME  TEXT      NOT NULL,
   PHONE       CHAR(50)  UNIQUE,
   EMAIL       CHAR(50)  UNIQUE,
   LOGIN       CHAR(50)  UNIQUE,
   PASSWORD    CHAR(50)  
);

CREATE TYPE typeofseat AS ENUM ('PARTER', 'BALCON', 'LODGE');

CREATE TABLE TICKETS(
   ID  SERIAL  PRIMARY KEY,
   SEATTYPE    typeofseat DEFAULT 'PARTER',
   SEATNUM     INTEGER    NOT NULL  
);

CREATE TABLE ACTIONS(
   ID  SERIAL   PRIMARY KEY,
   ACTIONNAME   TEXT      NOT NULL,
   ACTIONTYPE   TEXT      NOT NULL,  
   ACTIONDATE   TIMESTAMP
);

CREATE TYPE status AS ENUM ('PAYED', 'INWORK', 'REVOKED');

CREATE TABLE ORDERS(
   ID  SERIAL   PRIMARY KEY,
   ID_CLIENT    INTEGER  REFERENCES CLIENTS (ID),
   ID_ACTION    INTEGER  REFERENCES ACTIONS (ID),
   ID_TICKET    INTEGER  REFERENCES TICKETS (ID),
   ORDERSTATUS	status DEFAULT 'INWORK',
   FIRSTNAME    TEXT      NOT NULL,
   ORDERDATE    TIMESTAMP,
   PRICE		REAL
);




